echo "Adding DNS Entry"
sleep 2
ssh root@utility "echo 'JFRUTCA4NjQwMApsYWIuZXhhbXBsZS5jb20uIElOICBTT0Egbm9kZTUubGFiLmV4YW1wbGUuY29t
LiByb290Lm5vZGU1LmxhYi5leGFtcGxlLmNvbS4gKAogICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgIDIwMjIwNjEzMTUgICAgICA7IHNlcmlhbCBudW1iZXIKICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAxSCAgICAgICAgICAgICAgOyByZWZyZXNoIHNsYXZlCiAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgNU0gICAgICAgICAgICAgIDsgcmV0cnkgcXVlcnkKICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAxVyAgICAgICAgICAgICAgOyBleHBpcmUKICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAxTSAgICAgICAgICAgICAgOyBuZWdhdGl2ZSBUVEwK
KQo7IG93bmVyICAgICAgICAgICAgICAgICBUVEwgICAgIENMICB0eXBlICAgICAgICAgICAgICAg
IFJEQVRBCkAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgSU4gIE5TICAgICAgICAgIG5v
ZGU1LmxhYi5leGFtcGxlLmNvbS4KQCAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBJTiAg
TVggICAgICAgICAgMTAgIG5vZGU1LmxhYi5leGFtcGxlLmNvbS4KX2tlcmJlcm9zLW1hc3Rlci5f
dGNwLmxhYi5leGFtcGxlLmNvbS4gODY0MDAgSU4gU1JWIDAgMTAwIDg4IG5vZGU1LmxhYi5leGFt
cGxlLmNvbS4KX2tlcmJlcm9zLW1hc3Rlci5fdWRwLmxhYi5leGFtcGxlLmNvbS4gODY0MDAgSU4g
U1JWIDAgMTAwIDg4IG5vZGU1LmxhYi5leGFtcGxlLmNvbS4KX2tlcmJlcm9zLl90Y3AubGFiLmV4
YW1wbGUuY29tLiA4NjQwMCBJTiBTUlYgMCAxMDAgODggbm9kZTUubGFiLmV4YW1wbGUuY29tLgpf
a2VyYmVyb3MuX3VkcC5sYWIuZXhhbXBsZS5jb20uIDg2NDAwIElOIFNSViAwIDEwMCA4OCBub2Rl
NS5sYWIuZXhhbXBsZS5jb20uCl9rZXJiZXJvcy5sYWIuZXhhbXBsZS5jb20uIDg2NDAwIElOIFRY
VCAiTEFCLkVYQU1QTEUuQ09NIgpfa3Bhc3N3ZC5fdGNwLmxhYi5leGFtcGxlLmNvbS4gODY0MDAg
SU4gU1JWIDAgMTAwIDQ2NCBub2RlNS5sYWIuZXhhbXBsZS5jb20uCl9rcGFzc3dkLl91ZHAubGFi
LmV4YW1wbGUuY29tLiA4NjQwMCBJTiBTUlYgMCAxMDAgNDY0IG5vZGU1LmxhYi5leGFtcGxlLmNv
bS4KX2xkYXAuX3RjcC5sYWIuZXhhbXBsZS5jb20uIDg2NDAwIElOIFNSViAwIDEwMCAzODkgbm9k
ZTUubGFiLmV4YW1wbGUuY29tLgpjbGFzc3Jvb20gICAgICAgICAgICAgICAgICAgICAgIElOICBB
ICAgICAgICAgICAxNzIuMjUuMjU0LjI1NAp3b3Jrc3RhdGlvbiAgICAgICAgICAgICAgICAgICAg
IElOICBBICAgICAgICAgICAxNzIuMjUuMjUwLjkKbm9kZTEgICAgICAgICAgICAgICAgICAgICAg
ICAgICBJTiAgQSAgICAgICAgICAgMTcyLjI1LjI1MC4xMApub2RlMiAgICAgICAgICAgICAgICAg
ICAgICAgICAgIElOICBBICAgICAgICAgICAxNzIuMjUuMjUwLjExCm5vZGUzICAgICAgICAgICAg
ICAgICAgICAgICAgICAgSU4gIEEgICAgICAgICAgIDE3Mi4yNS4yNTAuMTIKbm9kZTQgICAgICAg
ICAgICAgICAgICAgICAgICAgICBJTiAgQSAgICAgICAgICAgMTcyLjI1LjI1MC4xMwpiYXN0aW9u
ICAgICAgICAgICAgICAgICAgICAgICAgIElOICBBICAgICAgICAgICAxNzIuMjUuMjUwLjI1NApu
b2RlNSAgICAgICAgICAgICAgICAgICAgICAgICAgIElOICBBICAgICAgICAgICAxNzIuMjUuMjUw
LjIyMApjb250ZW50ICAgICAgICAgICAgICAgICAgICAgICAgIElOIENOQU1FICAgICAgICBjbGFz
c3Jvb20ubGFiLmV4YW1wbGUuY29tLgptYXRlcmlhbHMgICAgICAgICAgICAgICAgICAgICAgIElO
IENOQU1FICAgICAgICBjbGFzc3Jvb20ubGFiLmV4YW1wbGUuY29tLgpyZWdpc3RyeSAgICAgICAg
ICAgICAgICAgICAgICAgIElOIENOQU1FICAgICAgICBub2RlNS5sYWIuZXhhbXBsZS5jb20uCnNl
cnZlcmEgICAgICAgICAgICAgICAgICAgICAgICAgSU4gQ05BTUUgICAgICAgIG5vZGUxLmxhYi5l
eGFtcGxlLmNvbS4Kc2VydmVyYiAgICAgICAgICAgICAgICAgICAgICAgICBJTiBDTkFNRSAgICAg
ICAgbm9kZTIubGFiLmV4YW1wbGUuY29tLgpzZXJ2ZXJjICAgICAgICAgICAgICAgICAgICAgICAg
IElOIENOQU1FICAgICAgICBub2RlMy5sYWIuZXhhbXBsZS5jb20uCnNlcnZlcmQgICAgICAgICAg
ICAgICAgICAgICAgICAgSU4gQ05BTUUgICAgICAgIG5vZGU0LmxhYi5leGFtcGxlLmNvbS4KdXRp
bGl0eSAgICAgICAgICAgICAgICAgICAgICAgICBJTiBDTkFNRSAgICAgICAgbm9kZTUubGFiLmV4
YW1wbGUuY29tLgo=' | base64 -d > /data/named/lab.example.com.zone" 


ssh root@utility "echo 'JFRUTCA4NjQwMAoyNTAuMjUuMTcyLklOLUFERFIuQVJQQS4gSU4gIFNPQSBub2RlNS5sYWIuZXhh
bXBsZS5jb20uIHJvb3Qubm9kZTUubGFiLmV4YW1wbGUuY29tLiAoCiAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgMjAyMjAxMDQxNSAgICAgIDsgc2VyaWFsIG51bWJlcgogICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgIDFIICAgICAgICAgICAgICA7IHJlZnJlc2ggc2xhdmUKICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICA1TSAgICAgICAgICAgICAgOyByZXRyeSBxdWVy
eQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDFXICAgICAgICAgICAgICA7IGV4cGly
ZQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDFNICAgICAgICAgICAgICA7IG5lZ2F0
aXZlIFRUTAopCgo7IG93bmVyICAgICAgICAgICAgICAgICBUVEwgICAgIENMICB0eXBlICAgICAg
ICBSREFUQQpAICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIElOICBOUyAgICAgICAgICBu
b2RlNS5sYWIuZXhhbXBsZS5jb20uCgo5ICAgICAgICAgICAgICAgICAgICAgICAgICAgSU4gIFBU
UiAgd29ya3N0YXRpb24ubGFiLmV4YW1wbGUuY29tLgoyNTQgICAgICAgICAgICAgICAgICAgICAg
ICAgSU4gIFBUUiAgYmFzdGlvbi5sYWIuZXhhbXBsZS5jb20uCjIyMCAgICAgICAgICAgICAgICAg
ICAgICAgICBJTiAgUFRSICBub2RlNS5sYWIuZXhhbXBsZS5jb20uCjEwICAgICAgICAgICAgICAg
ICAgICAgICAgICBJTiAgUFRSICBub2RlMS5sYWIuZXhhbXBsZS5jb20uCjExICAgICAgICAgICAg
ICAgICAgICAgICAgICBJTiAgUFRSICBub2RlMi5sYWIuZXhhbXBsZS5jb20uCjEyICAgICAgICAg
ICAgICAgICAgICAgICAgICBJTiAgUFRSICBub2RlMy5sYWIuZXhhbXBsZS5jb20uCjEzICAgICAg
ICAgICAgICAgICAgICAgICAgICBJTiAgUFRSICBub2RlNC5sYWIuZXhhbXBsZS5jb20uCg==' | base64 -d > /data/named/250.25.172.zone"


echo "Permission assinging in Progress..."
sleep 2
ssh root@utility  "chmod 644 /data/named/lab.example.com.zone"
ssh root@utility  "sed -i 's/\<80\>/8080/g' /etc/nginx/nginx.conf"
ssh root@utility  "systemctl restart nginx"
ssh root@utility  "firewall-cmd   --permanent  --add-port=8080/tcp"
ssh root@utility  "firewall-cmd --reload"
ssh root@servera  "hostnamectl set-hostname node1.lab.example.com ; hostname node1.lab.example.com"   > /dev/null 2>&1
ssh root@serverb  "hostnamectl set-hostname node2.lab.example.com ; hostname node2.lab.example.com"   > /dev/null 2>&1
ssh root@serverc  "hostnamectl set-hostname node3.lab.example.com ; hostname node3.lab.example.com"   > /dev/null 2>&1
ssh root@serverd  "hostnamectl set-hostname node4.lab.example.com ; hostname node4.lab.example.com"   > /dev/null 2>&1
ssh root@utility  "hostnamectl set-hostname node5.lab.example.com ; hostname node5.lab.example.com"   > /dev/null 2>&1

ssh root@servera  "echo 'exclude=python3*'  >>  /etc/dnf/dnf.conf"   > /dev/null 2>&1
ssh root@serverb  "echo 'exclude=python3*'  >>  /etc/dnf/dnf.conf"   > /dev/null 2>&1
ssh root@serverc  "echo 'exclude=python3*'  >>  /etc/dnf/dnf.conf"   > /dev/null 2>&1
ssh root@serverd  "echo 'exclude=python3*'  >>  /etc/dnf/dnf.conf"   > /dev/null 2>&1
ssh root@utility  "echo 'exclude=python3*'  >>  /etc/dnf/dnf.conf"   > /dev/null 2>&1


echo "Restarting DNS Service.."
sleep 2
ssh root@utility  "systemctl restart container-dns-subdomain.service"
echo "Finanlizing..."
sleep 2
echo "Done...(^.^)"
